import connectDB from '@/lib/mongodb';
import MenuItem from '@/models/MenuItem';

export async function POST() {
  try {
    await connectDB();

    // Clear existing items to allow re-seed
    await MenuItem.deleteMany({});

    const menuItems = [
      // ─── Coffee ───
      {
        title: 'Classic Espresso',
        price: 79,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600&q=80&auto=format&fit=crop',
        description: 'Rich and bold single-shot espresso with a golden crema on top',
        popular: true,
        prepTime: 5,
      },
      {
        title: 'Cappuccino',
        price: 119,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80&auto=format&fit=crop',
        description: 'Velvety steamed milk with rich espresso and thick milk foam art',
        popular: true,
        prepTime: 7,
      },
      {
        title: 'Latte',
        price: 129,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1561047029-3000c68339ca?w=600&q=80&auto=format&fit=crop',
        description: 'Smooth espresso with silky steamed milk and a delicate foam layer',
        popular: true,
        prepTime: 7,
      },
      {
        title: 'Mocha Coffee',
        price: 139,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1607345040012-d9d56ec82b1f?w=600&q=80&auto=format&fit=crop',
        description: 'Rich chocolate blended with espresso and creamy steamed milk',
        popular: false,
        prepTime: 8,
      },
      {
        title: 'Cold Coffee',
        price: 149,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&q=80&auto=format&fit=crop',
        description: 'Chilled coffee blended with milk and served over ice — refreshingly smooth',
        popular: true,
        prepTime: 6,
      },
      {
        title: 'Hazelnut Cold Coffee',
        price: 169,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&q=80&auto=format&fit=crop',
        description: 'Cold coffee with a rich hazelnut syrup twist, topped with whipped cream',
        popular: true,
        prepTime: 7,
      },
      {
        title: 'Caramel Latte',
        price: 159,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=600&q=80&auto=format&fit=crop',
        description: 'Espresso with vanilla, steamed milk, and a golden caramel drizzle',
        popular: true,
        prepTime: 8,
      },
      {
        title: 'Irish Coffee',
        price: 179,
        category: 'coffee',
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
        description: 'Warm coffee with a hint of Irish cream, topped with lightly whipped cream',
        popular: false,
        prepTime: 8,
      },

      // ─── Tea ───
      {
        title: 'Cutting Chai',
        price: 29,
        category: 'tea',
        image: 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=600&q=80&auto=format&fit=crop',
        description: 'Strong half-cup chai brewed with milk — Mumbai style, served hot',
        popular: true,
        prepTime: 4,
      },
      {
        title: 'Masala Chai',
        price: 49,
        category: 'tea',
        image: 'https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?w=600&q=80&auto=format&fit=crop',
        description: 'Traditional Indian spiced tea with cardamom, ginger, and cinnamon',
        popular: true,
        prepTime: 5,
      },
      {
        title: 'Ginger Tea',
        price: 59,
        category: 'tea',
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80&auto=format&fit=crop',
        description: 'Soothing hot tea with a bold ginger kick — perfect for any season',
        popular: false,
        prepTime: 5,
      },
      {
        title: 'Green Tea',
        price: 69,
        category: 'tea',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80&auto=format&fit=crop',
        description: 'Premium light green tea leaves steeped to a clean, antioxidant-rich brew',
        popular: false,
        prepTime: 5,
      },

      // ─── Refreshers ───
      {
        title: 'Lemon Iced Tea',
        price: 99,
        category: 'refreshers',
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80&auto=format&fit=crop',
        description: 'Chilled black tea with fresh lemon juice and a hint of mint',
        popular: false,
        prepTime: 5,
      },
      {
        title: 'Peach Iced Tea',
        price: 109,
        category: 'refreshers',
        image: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=600&q=80&auto=format&fit=crop',
        description: 'Fruity chilled tea infused with real peach flavour and ice',
        popular: true,
        prepTime: 5,
      },
      {
        title: 'Mojito Mint Cooler',
        price: 119,
        category: 'refreshers',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80&auto=format&fit=crop',
        description: 'Mint, lime, and sparkling soda — the ultimate non-alcoholic cooler',
        popular: true,
        prepTime: 6,
      },
      {
        title: 'Watermelon Cooler',
        price: 129,
        category: 'refreshers',
        image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80&auto=format&fit=crop',
        description: 'Fresh watermelon juice blended with mint and chilled to perfection',
        popular: true,
        prepTime: 6,
      },

      // ─── Snacks & Quick Bites ───
      {
        title: 'Veg Sandwich',
        price: 99,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=600&q=80&auto=format&fit=crop',
        description: 'Fresh vegetables with chutneys and cheese between toasted bread slices',
        popular: false,
        prepTime: 8,
      },
      {
        title: 'Cheese Grilled Sandwich',
        price: 129,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&q=80&auto=format&fit=crop',
        description: 'Golden grilled sandwich loaded with melted cheese and herbs',
        popular: true,
        prepTime: 10,
      },
      {
        title: 'Paneer Tikka Sandwich',
        price: 149,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=600&q=80&auto=format&fit=crop',
        description: 'Spiced tikka paneer in a crispy grilled sandwich with mint chutney',
        popular: true,
        prepTime: 12,
      },
      {
        title: 'French Fries',
        price: 89,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1583339793403-3d9b001b6008?w=600&q=80&auto=format&fit=crop',
        description: 'Crispy golden potato fries seasoned with sea salt, served hot',
        popular: true,
        prepTime: 8,
      },
      {
        title: 'Peri Peri Fries',
        price: 109,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=600&q=80&auto=format&fit=crop',
        description: 'Crispy fries tossed in a bold, fiery peri peri seasoning blend',
        popular: true,
        prepTime: 9,
      },
      {
        title: 'Garlic Bread',
        price: 119,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80&auto=format&fit=crop',
        description: 'Crusty bread toasted with herb butter and roasted garlic',
        popular: false,
        prepTime: 8,
      },
      {
        title: 'Cheese Garlic Bread',
        price: 149,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&q=80&auto=format&fit=crop',
        description: 'Garlic butter toast topped with a generous melted cheese crust',
        popular: true,
        prepTime: 10,
      },
      {
        title: 'Veg Burger',
        price: 139,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1550950158-d0d960dff596?w=600&q=80&auto=format&fit=crop',
        description: 'Juicy veggie patty with fresh lettuce, tomato, and zesty sauce in a soft bun',
        popular: false,
        prepTime: 12,
      },
      {
        title: 'Crispy Paneer Burger',
        price: 169,
        category: 'snacks',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80&auto=format&fit=crop',
        description: 'Crispy fried paneer patty with coleslaw, cheese, and sriracha mayo',
        popular: true,
        prepTime: 14,
      },

      // ─── Pizza & Pasta ───
      {
        title: 'Margherita Pizza',
        price: 199,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80&auto=format&fit=crop',
        description: 'Classic pizza with rich tomato sauce, fresh mozzarella, and basil',
        popular: true,
        prepTime: 15,
      },
      {
        title: 'Farm Fresh Pizza',
        price: 249,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80&auto=format&fit=crop',
        description: 'Loaded with seasonal veggies on a herbed tomato base with mozzarella',
        popular: false,
        prepTime: 17,
      },
      {
        title: 'Paneer Supreme Pizza',
        price: 289,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80&auto=format&fit=crop',
        description: 'Spiced paneer tikka topping on a creamy white sauce pizza base',
        popular: true,
        prepTime: 18,
      },
      {
        title: 'White Sauce Pasta',
        price: 189,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80&auto=format&fit=crop',
        description: 'Penne in a rich, creamy béchamel sauce with herbs and parmesan',
        popular: true,
        prepTime: 14,
      },
      {
        title: 'Red Sauce Pasta',
        price: 179,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=600&q=80&auto=format&fit=crop',
        description: 'Al dente pasta in a robust tomato and basil marinara sauce',
        popular: false,
        prepTime: 14,
      },
      {
        title: 'Pink Sauce Pasta',
        price: 209,
        category: 'pizza',
        image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80&auto=format&fit=crop',
        description: 'Creamy tomato-infused rose sauce pasta — the best of both worlds',
        popular: true,
        prepTime: 15,
      },

      // ─── Desserts ───
      {
        title: 'Brownie',
        price: 99,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=600&q=80&auto=format&fit=crop',
        description: 'Dense, fudgy chocolate brownie with a rich crackly top crust',
        popular: true,
        prepTime: 5,
      },
      {
        title: 'Brownie with Ice Cream',
        price: 149,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80&auto=format&fit=crop',
        description: 'Warm chocolate brownie paired with a scoop of vanilla ice cream',
        popular: true,
        prepTime: 6,
      },
      {
        title: 'Chocolate Pastry',
        price: 89,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80&auto=format&fit=crop',
        description: 'Moist chocolate sponge cake layered with chocolate ganache frosting',
        popular: false,
        prepTime: 5,
      },
      {
        title: 'Cheesecake Slice',
        price: 169,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80&auto=format&fit=crop',
        description: 'New York style baked cheesecake on a buttery graham cracker crust',
        popular: true,
        prepTime: 5,
      },
      {
        title: 'Choco Lava Cake',
        price: 119,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1617305855105-a1d1a4b4c5e3?w=600&q=80&auto=format&fit=crop',
        description: 'Warm chocolate cake with a gooey molten chocolate centre inside',
        popular: true,
        prepTime: 10,
      },
      {
        title: 'Ice Cream Sundae',
        price: 139,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80&auto=format&fit=crop',
        description: 'Three scoops of ice cream topped with hot fudge, nuts, and a cherry',
        popular: false,
        prepTime: 5,
      },

      // ─── Milkshakes & Smoothies ───
      {
        title: 'Chocolate Shake',
        price: 139,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1572490122747-3e9b6dabb5d3?w=600&q=80&auto=format&fit=crop',
        description: 'Thick, creamy chocolate milkshake blended with premium ice cream',
        popular: true,
        prepTime: 6,
      },
      {
        title: 'Oreo Shake',
        price: 159,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80&auto=format&fit=crop',
        description: 'Cookies and cream shake blended with real Oreo biscuits and milk',
        popular: true,
        prepTime: 7,
      },
      {
        title: 'KitKat Shake',
        price: 169,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
        description: 'Creamy milkshake blended with KitKat pieces and topped with whipped cream',
        popular: true,
        prepTime: 7,
      },
      {
        title: 'Strawberry Shake',
        price: 149,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
        description: 'Bright pink strawberry milkshake with real fruit blended in',
        popular: false,
        prepTime: 6,
      },
      {
        title: 'Mango Smoothie',
        price: 159,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
        description: 'Fresh Alphonso mango blended into a thick, tropical smoothie',
        popular: true,
        prepTime: 6,
      },
      {
        title: 'Banana Peanut Smoothie',
        price: 169,
        category: 'milkshakes',
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
        description: 'Power-packed banana and peanut butter smoothie with honey',
        popular: false,
        prepTime: 6,
      },

      // ─── Combos ───
      {
        title: 'Coffee + Sandwich',
        price: 199,
        category: 'combos',
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80&auto=format&fit=crop',
        description: 'Any coffee of your choice paired with a freshly made veg sandwich',
        popular: true,
        prepTime: 12,
      },
      {
        title: 'Burger + Fries + Coke',
        price: 249,
        category: 'combos',
        image: 'https://images.unsplash.com/photo-1550950158-d0d960dff596?w=600&q=80&auto=format&fit=crop',
        description: 'Crispy veg burger, golden fries, and a chilled Coke — the classic trio',
        popular: true,
        prepTime: 15,
      },
      {
        title: 'Pizza + Cold Coffee',
        price: 349,
        category: 'combos',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80&auto=format&fit=crop',
        description: 'Any personal pizza paired with a refreshing chilled cold coffee',
        popular: true,
        prepTime: 18,
      },
      {
        title: 'Pasta + Mojito',
        price: 299,
        category: 'combos',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80&auto=format&fit=crop',
        description: 'A bowl of pasta with a Mojito Mint Cooler on the side',
        popular: false,
        prepTime: 17,
      },
      {
        title: 'Couple Combo',
        price: 499,
        category: 'combos',
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80&auto=format&fit=crop',
        description: '2 coffees + 1 pizza + 1 dessert — the perfect date at BrewHub',
        popular: true,
        prepTime: 20,
      },

      // ─── Signature Specials ───
      {
        title: 'BrewHub Special Coffee',
        price: 199,
        category: 'specials',
        image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80&auto=format&fit=crop',
        description: 'Our secret-recipe house blend — a multi-layered coffee experience',
        popular: true,
        prepTime: 10,
      },
      {
        title: 'Smoky Paneer Platter',
        price: 299,
        category: 'specials',
        image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=600&q=80&auto=format&fit=crop',
        description: 'Smoky grilled paneer skewers with mint chutney and spiced onion salad',
        popular: true,
        prepTime: 18,
      },
      {
        title: 'Loaded Nachos',
        price: 249,
        category: 'specials',
        image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&q=80&auto=format&fit=crop',
        description: 'Crunchy nachos piled high with cheese, jalapeños, salsa, and sour cream',
        popular: true,
        prepTime: 12,
      },
      {
        title: 'Cafe Special Sizzler',
        price: 399,
        category: 'specials',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80&auto=format&fit=crop',
        description: 'A sizzling iron platter with paneer, grilled veggies, rice, and fries',
        popular: true,
        prepTime: 20,
      },
    ];

    const items = await MenuItem.insertMany(menuItems);
    return Response.json(
      { message: 'BrewHub Karjat menu seeded successfully!', count: items.length },
      { status: 201 }
    );
  } catch (error) {
    console.error('Seed error:', error);
    return Response.json({ error: 'Internal server error' }, { status: 500 });
  }
}
